services:
  - type: web
    name: herbszen
    runtime: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: SMTP_USER
        value: herbszen007@gmail.com
      - key: SMTP_PASS
        sync: false
      - key: MONGODB_URI
        sync: false
